site_name: SequenceAligner
site_description: 'Documentation for a simple alignment tool for DNA sequences.'
site_author: 'Abhinav Mishra'
site_url: https://bibymaths.github.io/SequenceAligner
use_directory_urls: false
repo_url: https://github.com/bibymaths/SequenceAligner

theme:
  name: readthedocs
  language: en
  features:
    - navigation.tabs
    - content.code.copy

nav:
  - Home: index.md
  - API Reference: api/html/index.html
  - Theoretical Background: processes.md
  - Output: outputs.md
  - About: about.md

markdown_extensions:
  - pymdownx.arithmatex:
      inline_syntax: [ '$', '$' ]
      block_syntax: [ '$$', '$$' ]
  - toc:
      permalink: true
  - admonition
  - codehilite

plugins:
  - search

watch:
  - docs

copyright: >
  Copyright &copy; 2025 <a href="https://bibymaths.github.io">Abhinav Mishra</a>.