[tool.poetry]
name = "sequencealigner"
version = "0.1.0"
description = ""
authors = ["Abhinav Mishra <mishraabhinav36@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
datashader = "^0.18.1"
dask = "^2025.5.0"
pyarrow = "^20.0.0"
ome-zarr = "^0.11.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
