import React from 'react';

// This component will display parsed TSV/CSV tables with links to their
// corresponding figures. For demonstration purposes, it renders a static
// list. In production, you would query the backend for available
// analysis files and parse them into tables using react-table or similar.

function AnalysisDashboard() {
  return (
    <div className="border p-2 mt-4 bg-white">
      <h3 className="font-semibold mb-2">Analysis Dashboard</h3>
      <p>This area will show tables and charts generated by downstream analysis.</p>
      <ul className="list-disc list-inside">
        <li>Global alignment summary (table + heatmap)</li>
        <li>Local alignment summary (table + heatmap)</li>
        <li>LCS alignment summary (table + heatmap)</li>
      </ul>
    </div>
  );
}

export default AnalysisDashboard;