"""
FastAPI backend for the sequence alignment web platform.

This module defines endpoints to upload FASTA files, create alignment sessions,
run C++ alignment tools with intelligent selection, stream live logs via
WebSockets, and expose downstream analysis outputs. It uses a simple
directory-based session management scheme where each run is stored under
``data/sessions/{uuid}`` with a metadata JSON. The alignment work is
performed asynchronously through background tasks so that the API remains
responsive. This skeleton is intended as a starting point and does not
perform actual sequence alignment – instead it simulates long‑running work.
"""

import asyncio
import json
import logging
import shutil
import uuid
from datetime import datetime
from pathlib import Path
from typing import List


from fastapi import BackgroundTasks, FastAPI, File, HTTPException, UploadFile, WebSocket, WebSocketDisconnect
from fastapi.responses import FileResponse, JSONResponse
from pydantic import BaseModel

from .common import BASE_DATA_DIR, manager
from .alignment_runner import run_alignment
from .analysis_parser import discover_analysis_outputs, parse_tsv

app = FastAPI(title="Sequence Alignment Platform")

BASE_DATA_DIR = Path("data/sessions")
BASE_DATA_DIR.mkdir(parents=True, exist_ok=True)

logger = logging.getLogger("uvicorn")

@app.get("/")
async def root():
    return {"message": "Sequence Alignment API is up and running!"}

class AlignmentRequest(BaseModel):
    gap_open: float = 10.0
    gap_extend: float = 0.5
    mode: str = "global"  # global, local, lcs, or all


class SessionMetadata(BaseModel):
    session_id: str
    timestamp: str
    query_filename: str
    target_filename: str
    parameters: dict
    status: str


def create_session_dir() -> Path:
    """Create a new session directory and return its path."""
    sid = str(uuid.uuid4())
    session_dir = BASE_DATA_DIR / sid
    session_dir.mkdir(parents=True, exist_ok=False)
    return session_dir


def write_metadata(session_dir: Path, query_file: str, target_file: str, params: dict, status: str) -> SessionMetadata:
    """Persist session metadata to disk and return the typed object."""
    metadata = SessionMetadata(
        session_id=session_dir.name,
        timestamp=datetime.utcnow().isoformat(),
        query_filename=query_file,
        target_filename=target_file,
        parameters=params,
        status=status,
    )
    with open(session_dir / "metadata.json", "w", encoding="utf-8") as fh:
        json.dump(metadata.dict(), fh, indent=2)
    return metadata


async def update_status(session_dir: Path, status: str) -> None:
    """Update the stored status in metadata.json for the session."""
    meta_path = session_dir / "metadata.json"
    if not meta_path.exists():
        return
    with open(meta_path, "r", encoding="utf-8") as fh:
        data = json.load(fh)
    data["status"] = status
    with open(meta_path, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=2)


@app.post("/align")
async def align(
    background_tasks: BackgroundTasks,
    query: UploadFile = File(...),
    target: UploadFile = File(...),
    gap_open: float = 10.0,
    gap_extend: float = 0.5,
    mode: str = "global",
) -> SessionMetadata:
    """
    Upload two FASTA files and initiate an alignment session.

    This endpoint saves the uploaded files under a new session directory,
    writes metadata, and triggers the alignment task asynchronously.
    """
    if mode not in {"global", "local", "lcs", "all"}:
        raise HTTPException(status_code=400, detail="Invalid mode")

    session_dir = create_session_dir()

    # Save uploaded files
    query_path = session_dir / query.filename
    target_path = session_dir / target.filename
    with open(query_path, "wb") as fq:
        shutil.copyfileobj(query.file, fq)
    with open(target_path, "wb") as ft:
        shutil.copyfileobj(target.file, ft)

    params = {"gap_open": gap_open, "gap_extend": gap_extend, "mode": mode}
    metadata = write_metadata(session_dir, query.filename, target.filename, params, status="queued")

    # Kick off alignment in the background
    background_tasks.add_task(run_alignment, session_dir, query_path, target_path, params)

    return metadata


@app.get("/session/{session_id}")
async def get_session_metadata(session_id: str) -> SessionMetadata:
    """Return metadata for a given session."""
    meta_path = BASE_DATA_DIR / session_id / "metadata.json"
    if not meta_path.exists():
        raise HTTPException(status_code=404, detail="Session not found")
    with open(meta_path, "r", encoding="utf-8") as fh:
        data = json.load(fh)
    return SessionMetadata(**data)


@app.get("/session/{session_id}/results")
async def list_results(session_id: str) -> JSONResponse:
    """List files generated by the alignment within the session."""
    session_dir = BASE_DATA_DIR / session_id
    if not session_dir.exists():
        raise HTTPException(status_code=404, detail="Session not found")
    files = []
    for path in session_dir.glob("**/*"):
        if path.is_file():
            files.append(str(path.relative_to(session_dir)))
    return JSONResponse({"files": files})


@app.get("/session/{session_id}/analysis")
async def list_analysis(session_id: str) -> JSONResponse:
    """Discover and return structured information about analysis outputs."""
    session_dir = BASE_DATA_DIR / session_id
    analysis_dir = session_dir / "analysis_out"
    if not analysis_dir.exists():
        raise HTTPException(status_code=404, detail="No analysis outputs found")
    data = discover_analysis_outputs(analysis_dir)
    return JSONResponse(data)


@app.get("/session/{session_id}/analysis/table/{filename}")
async def get_analysis_table(session_id: str, filename: str) -> JSONResponse:
    """Return parsed TSV or CSV file as JSON."""
    session_dir = BASE_DATA_DIR / session_id
    file_path = session_dir / "analysis_out" / filename
    if not file_path.exists():
        raise HTTPException(status_code=404, detail="File not found")
    records = parse_tsv(file_path)
    return JSONResponse({"records": records})


@app.get("/session/{session_id}/file/{path:path}")
async def get_file(session_id: str, path: str):
    """Serve an arbitrary file from within a session. Use with caution."""
    file_path = BASE_DATA_DIR / session_id / path
    if not file_path.exists() or not file_path.is_file():
        raise HTTPException(status_code=404, detail="File not found")
    return FileResponse(file_path)


class ConnectionManager:
    """Manages WebSocket connections and message queues per session."""

    def __init__(self) -> None:
        self.active_connections: dict[str, List[WebSocket]] = {}
        self.log_queues: dict[str, asyncio.Queue] = {}

    async def connect(self, session_id: str, websocket: WebSocket) -> None:
        await websocket.accept()
        self.active_connections.setdefault(session_id, []).append(websocket)
        self.log_queues.setdefault(session_id, asyncio.Queue())

    def disconnect(self, session_id: str, websocket: WebSocket) -> None:
        if session_id in self.active_connections:
            self.active_connections[session_id].remove(websocket)

    async def broadcast(self, session_id: str, message: str) -> None:
        for ws in self.active_connections.get(session_id, []):
            await ws.send_text(message)

    def get_queue(self, session_id: str) -> asyncio.Queue:
        return self.log_queues.setdefault(session_id, asyncio.Queue())


manager = ConnectionManager()


@app.websocket("/ws/logs/{session_id}")
async def websocket_endpoint(websocket: WebSocket, session_id: str) -> None:
    """
    WebSocket endpoint that streams logs for a given session.

    Background tasks push messages into the queue associated with the session.
    This coroutine pops them and forwards to the connected client.
    """
    await manager.connect(session_id, websocket)
    queue = manager.get_queue(session_id)
    try:
        while True:
            msg = await queue.get()
            await websocket.send_text(msg)
    except WebSocketDisconnect:
        manager.disconnect(session_id, websocket)
        logger.info(f"WebSocket disconnected for session {session_id}")
